/* SPDX-License-Identifier: BSD-3-Clause
* Copyright(c) 2017-2018 Intel Corporation
*/

#define RTE_EXEC_ENV "windowsapp"
#define RTE_EXEC_ENV_WINDOWSAPP 1
#define RTE_MACHINE "native"
#define RTE_ARCH "x86_64"
#define RTE_ARCH_X86_64 1
#define RTE_TOOLCHAIN "icc"
#define RTE_TOOLCHAIN_ICC 1
#undef RTE_LIBC
#undef RTE_LIBC_NEWLIB_SRC
#undef RTE_LIBC_NEWLIB_BIN
#undef RTE_LIBC_NETINCS
#undef RTE_LIBGLOSS

#define RTE_MAX_MEMSEG_LISTS 128
#define RTE_MAX_MEMSEG_PER_LIST 8192
#define RTE_LIBRTE_EAL 1
#define RTE_MAX_LCORE 128
#define RTE_MAX_NUMA_NODES 8
#define RTE_MAX_MEMSEG 256
#define RTE_MAX_MEMZONE 2560
#define RTE_MAX_TAILQ 32
#define RTE_LOG_LEVEL RTE_LOG_DEBUG
#define RTE_LOG_DP_LEVEL RTE_LOG_DEBUG
#define RTE_LOG_HISTORY 256
#undef RTE_LIBEAL_USE_HPET
#undef RTE_EAL_ALLOW_INV_SOCKET_ID
#undef RTE_EAL_ALWAYS_PANIC_ON_ERROR
#undef RTE_EAL_UNBIND_PORTS
#define RTE_LIBRTE_EAL_LINUXAPP 1
#undef RTE_LIBRTE_EAL_BAREMETAL
#define RTE_ENABLE_AVX 1
#undef RTE_ENABLE_AVX512
#undef RTE_LIBRTE_EAL_VMWARE_TSC_MAP_SUPPORT
#define RTE_LIBRTE_PCI 1
#define RTE_LIBRTE_KVARGS 1
#define RTE_LIBRTE_ETHDEV 1
#undef RTE_LIBRTE_ETHDEV_DEBUG
#define RTE_MAX_ETHPORTS 32
#define RTE_MAX_QUEUES_PER_PORT 1024
#undef RTE_LIBRTE_IEEE1588
#define RTE_ETHDEV_QUEUE_STAT_CNTRS 16
#define RTE_ETHDEV_RXTX_CALLBACKS 1
#undef RTE_ETHDEV_PROFILE_ITT_WASTED_RX_ITERATIONS
#undef RTE_ETHDEV_TX_PREPARE_NOOP
#define RTE_LIBRTE_PCI_BUS 1
#undef RTE_LIBRTE_ENA_PMD
#undef RTE_LIBRTE_ENA_DEBUG_RX
#undef RTE_LIBRTE_ENA_DEBUG_TX
#undef RTE_LIBRTE_ENA_DEBUG_TX_FREE
#undef RTE_LIBRTE_ENA_DEBUG_DRIVER
#undef RTE_LIBRTE_ENA_COM_DEBUG
#define RTE_LIBRTE_EM_PMD 1
#define RTE_LIBRTE_IGB_PMD 1
#undef RTE_LIBRTE_E1000_DEBUG_INIT
#undef RTE_LIBRTE_E1000_DEBUG_RX
#undef RTE_LIBRTE_E1000_DEBUG_TX
#undef RTE_LIBRTE_E1000_DEBUG_TX_FREE
#undef RTE_LIBRTE_E1000_DEBUG_DRIVER
#undef RTE_LIBRTE_E1000_PF_DISABLE_STRIP_CRC
#define RTE_LIBRTE_IXGBE_PMD 1
#undef RTE_LIBRTE_IXGBE_DEBUG_INIT
#undef RTE_LIBRTE_IXGBE_DEBUG_RX
#undef RTE_LIBRTE_IXGBE_DEBUG_TX
#undef RTE_LIBRTE_IXGBE_DEBUG_TX_FREE
#undef RTE_LIBRTE_IXGBE_DEBUG_DRIVER
#undef RTE_LIBRTE_IXGBE_PF_DISABLE_STRIP_CRC
#define RTE_IXGBE_INC_VECTOR 1
#undef RTE_LIBRTE_IXGBE_BYPASS
#define RTE_LIBRTE_I40E_PMD 1
#undef RTE_LIBRTE_I40E_DEBUG_RX
#undef RTE_LIBRTE_I40E_DEBUG_TX
#undef RTE_LIBRTE_I40E_DEBUG_TX_FREE
#define RTE_LIBRTE_I40E_RX_ALLOW_BULK_ALLOC 1
#define RTE_LIBRTE_I40E_INC_VECTOR 1
#undef RTE_LIBRTE_I40E_16BYTE_RX_DESC
#define RTE_LIBRTE_I40E_QUEUE_NUM_PER_PF 64
#define RTE_LIBRTE_I40E_QUEUE_NUM_PER_VF 4
#define RTE_LIBRTE_I40E_QUEUE_NUM_PER_VM 4
#define RTE_LIBRTE_I40E_ITR_INTERVAL -1
#undef RTE_LIBRTE_FM10K_PMD
#undef RTE_LIBRTE_FM10K_DEBUG_INIT
#undef RTE_LIBRTE_FM10K_DEBUG_RX
#undef RTE_LIBRTE_FM10K_DEBUG_TX
#undef RTE_LIBRTE_FM10K_DEBUG_TX_FREE
#undef RTE_LIBRTE_FM10K_DEBUG_DRIVER
#define RTE_LIBRTE_FM10K_RX_OLFLAGS_ENABLE 1
#define RTE_LIBRTE_FM10K_INC_VECTOR 1
#undef RTE_LIBRTE_MLX4_PMD
#undef RTE_LIBRTE_MLX4_DEBUG
#undef RTE_LIBRTE_MLX4_DEBUG_BROKEN_VERBS
#define RTE_LIBRTE_MLX4_TX_MP_CACHE 8
#undef RTE_LIBRTE_MLX5_PMD
#undef RTE_LIBRTE_MLX5_DEBUG
#define RTE_LIBRTE_MLX5_TX_MP_CACHE 8
#undef RTE_LIBRTE_BNX2X_PMD
#undef RTE_LIBRTE_BNX2X_DEBUG
#undef RTE_LIBRTE_BNX2X_DEBUG_INIT
#undef RTE_LIBRTE_BNX2X_DEBUG_RX
#undef RTE_LIBRTE_BNX2X_DEBUG_TX
#undef RTE_LIBRTE_BNX2X_MF_SUPPORT
#undef RTE_LIBRTE_BNX2X_DEBUG_PERIODIC
#undef RTE_LIBRTE_CXGBE_PMD 
#undef RTE_LIBRTE_CXGBE_DEBUG
#undef RTE_LIBRTE_CXGBE_DEBUG_REG
#undef RTE_LIBRTE_CXGBE_DEBUG_MBOX
#undef RTE_LIBRTE_CXGBE_DEBUG_TX
#undef RTE_LIBRTE_CXGBE_DEBUG_RX
#undef RTE_LIBRTE_CXGBE_TPUT
#undef RTE_LIBRTE_ENIC_PMD
#undef RTE_LIBRTE_ENIC_DEBUG
#undef RTE_LIBRTE_ENIC_DEBUG_FLOW 
#undef RTE_LIBRTE_NFP_PMD
#undef RTE_LIBRTE_NFP_DEBUG
#undef RTE_LIBRTE_MRVL_PMD
#undef RTE_LIBRTE_BNXT_PMD
#undef RTE_LIBRTE_SFC_EFX_PMD
#undef RTE_LIBRTE_SFC_EFX_DEBUG
#define RTE_LIBRTE_PMD_SOFTNIC 1
#undef RTE_LIBRTE_PMD_SZEDATA2
#define RTE_LIBRTE_PMD_SZEDATA2_AS 0
#undef RTE_LIBRTE_THUNDERX_NICVF_PMD
#undef RTE_LIBRTE_THUNDERX_NICVF_DEBUG_INIT
#undef RTE_LIBRTE_THUNDERX_NICVF_DEBUG_RX
#undef RTE_LIBRTE_THUNDERX_NICVF_DEBUG_TX
#undef RTE_LIBRTE_THUNDERX_NICVF_DEBUG_DRIVER
#undef RTE_LIBRTE_THUNDERX_NICVF_DEBUG_MBOX
#undef RTE_LIBRTE_LIO_PMD
#undef RTE_LIBRTE_LIO_DEBUG_DRIVER
#undef RTE_LIBRTE_LIO_DEBUG_INIT
#undef RTE_LIBRTE_LIO_DEBUG_RX
#undef RTE_LIBRTE_LIO_DEBUG_TX
#undef RTE_LIBRTE_LIO_DEBUG_MBOX
#undef RTE_LIBRTE_LIO_DEBUG_REGS
#undef RTE_LIBRTE_DPAA_BUS
#undef RTE_LIBRTE_DPAA_MEMPOOL
#undef RTE_LIBRTE_DPAA_PMD
#undef RTE_LIBRTE_OCTEONTX_PMD
#undef RTE_LIBRTE_OCTEONTX_DEBUG_INIT
#undef RTE_LIBRTE_OCTEONTX_DEBUG_RX
#undef RTE_LIBRTE_OCTEONTX_DEBUG_TX
#undef RTE_LIBRTE_OCTEONTX_DEBUG_DRIVER
#undef RTE_LIBRTE_OCTEONTX_DEBUG_MBOX
#undef RTE_LIBRTE_FSLMC_BUS
#undef RTE_LIBRTE_DPAA2_MEMPOOL
#undef RTE_LIBRTE_DPAA2_USE_PHYS_IOVA
#undef RTE_LIBRTE_DPAA2_PMD
#undef RTE_LIBRTE_DPAA2_DEBUG_INIT
#undef RTE_LIBRTE_DPAA2_DEBUG_DRIVER
#undef RTE_LIBRTE_DPAA2_DEBUG_RX
#undef RTE_LIBRTE_DPAA2_DEBUG_TX
#undef RTE_LIBRTE_DPAA2_DEBUG_TX_FREE
#undef RTE_LIBRTE_VIRTIO_PMD
#undef RTE_LIBRTE_VIRTIO_DEBUG_INIT
#undef RTE_LIBRTE_VIRTIO_DEBUG_RX
#undef RTE_LIBRTE_VIRTIO_DEBUG_TX
#undef RTE_LIBRTE_VIRTIO_DEBUG_DRIVER
#undef RTE_LIBRTE_VIRTIO_DEBUG_DUMP
#undef RTE_VIRTIO_USER
#undef RTE_LIBRTE_VMXNET3_PMD
#undef RTE_LIBRTE_VMXNET3_DEBUG_INIT
#undef RTE_LIBRTE_VMXNET3_DEBUG_RX
#undef RTE_LIBRTE_VMXNET3_DEBUG_TX
#undef RTE_LIBRTE_VMXNET3_DEBUG_TX_FREE
#undef RTE_LIBRTE_VMXNET3_DEBUG_DRIVER
#define RTE_LIBRTE_PMD_RING 1
#define RTE_PMD_RING_MAX_RX_RINGS 16
#define RTE_PMD_RING_MAX_TX_RINGS 16
#define RTE_LIBRTE_PMD_PCAP 1
#undef RTE_LIBRTE_PMD_BOND
#undef RTE_LIBRTE_BOND_DEBUG_ALB
#undef RTE_LIBRTE_BOND_DEBUG_ALB_L1
#undef RTE_LIBRTE_QEDE_PMD
#undef RTE_LIBRTE_QEDE_DEBUG_INIT
#undef RTE_LIBRTE_QEDE_DEBUG_INFO
#undef RTE_LIBRTE_QEDE_DEBUG_DRIVER
#undef RTE_LIBRTE_QEDE_DEBUG_TX
#undef RTE_LIBRTE_QEDE_DEBUG_RX
#define RTE_LIBRTE_QEDE_FW ""
#undef RTE_LIBRTE_PMD_AF_PACKET
#undef RTE_LIBRTE_ARK_PMD
#undef RTE_LIBRTE_ARK_PAD_TX
#undef RTE_LIBRTE_ARK_DEBUG_RX
#undef RTE_LIBRTE_ARK_DEBUG_TX
#undef RTE_LIBRTE_ARK_DEBUG_STATS
#undef RTE_LIBRTE_ARK_DEBUG_TRACE
#undef RTE_LIBRTE_AVP_PMD
#undef RTE_LIBRTE_AVP_DEBUG_RX
#undef RTE_LIBRTE_AVP_DEBUG_TX
#undef RTE_LIBRTE_AVP_DEBUG_DRIVER
#undef RTE_LIBRTE_AVP_DEBUG_BUFFERS
#undef RTE_LIBRTE_PMD_TAP
#undef RTE_LIBRTE_PMD_NULL
#undef RTE_LIBRTE_PMD_FAILSAFE
#define RTE_PMD_PACKET_PREFETCH 1
#define RTE_LIBRTE_CRYPTODEV 1
#undef RTE_LIBRTE_CRYPTODEV_DEBUG
#define RTE_CRYPTO_MAX_DEVS 64
#define RTE_CRYPTODEV_NAME_LEN 64
#undef RTE_LIBRTE_PMD_ARMV8_CRYPTO
#undef RTE_LIBRTE_PMD_ARMV8_CRYPTO_DEBUG
#undef RTE_LIBRTE_PMD_DPAA2_SEC
#undef RTE_LIBRTE_DPAA2_SEC_DEBUG_INIT
#undef RTE_LIBRTE_DPAA2_SEC_DEBUG_DRIVER
#undef RTE_LIBRTE_DPAA2_SEC_DEBUG_RX
#undef RTE_LIBRTE_PMD_DPAA_SEC
#undef RTE_LIBRTE_DPAA_SEC_DEBUG_INIT
#undef RTE_LIBRTE_DPAA_SEC_DEBUG_DRIVER
#undef RTE_LIBRTE_DPAA_SEC_DEBUG_RX
#undef RTE_LIBRTE_PMD_QAT
#undef RTE_LIBRTE_PMD_QAT_DEBUG_INIT
#undef RTE_LIBRTE_PMD_QAT_DEBUG_TX
#undef RTE_LIBRTE_PMD_QAT_DEBUG_RX
#undef RTE_LIBRTE_PMD_QAT_DEBUG_DRIVER
#define RTE_QAT_PMD_MAX_NB_SESSIONS 2048
#undef RTE_LIBRTE_PMD_AESNI_MB
#undef RTE_LIBRTE_PMD_AESNI_MB_DEBUG
#undef RTE_LIBRTE_PMD_OPENSSL
#undef RTE_LIBRTE_PMD_OPENSSL_DEBUG
#undef RTE_LIBRTE_PMD_AESNI_GCM
#undef RTE_LIBRTE_PMD_AESNI_GCM_DEBUG
#undef RTE_LIBRTE_PMD_SNOW3G
#undef RTE_LIBRTE_PMD_SNOW3G_DEBUG
#undef RTE_LIBRTE_PMD_KASUMI
#undef RTE_LIBRTE_PMD_KASUMI_DEBUG
#undef RTE_LIBRTE_PMD_ZUC
#undef RTE_LIBRTE_PMD_ZUC_DEBUG
#undef RTE_LIBRTE_PMD_CRYPTO_SCHEDULER
#undef RTE_LIBRTE_PMD_CRYPTO_SCHEDULER_DEBUG
#undef RTE_LIBRTE_PMD_NULL_CRYPTO
#undef RTE_LIBRTE_PMD_MRVL_CRYPTO
#undef RTE_LIBRTE_PMD_MRVL_CRYPTO_DEBUG
#define RTE_LIBRTE_SECURITY 1
#define RTE_LIBRTE_EVENTDEV 1
#undef RTE_LIBRTE_EVENTDEV_DEBUG
#define RTE_EVENT_MAX_DEVS 16
#define RTE_EVENT_MAX_QUEUES_PER_DEV 64
#define RTE_LIBRTE_PMD_SKELETON_EVENTDEV 1
#undef RTE_LIBRTE_PMD_SKELETON_EVENTDEV_DEBUG
#define RTE_LIBRTE_PMD_SW_EVENTDEV 1
#undef RTE_LIBRTE_PMD_SW_EVENTDEV_DEBUG
#undef RTE_LIBRTE_PMD_OCTEONTX_SSOVF
#undef RTE_LIBRTE_PMD_OCTEONTX_SSOVF_DEBUG
#define RTE_LIBRTE_RING 1
#undef RTE_LIBRTE_RING_DEBUG
#define RTE_LIBRTE_MEMPOOL 1
#define RTE_MEMPOOL_CACHE_MAX_SIZE 512
#undef RTE_LIBRTE_MEMPOOL_DEBUG
#define RTE_DRIVER_MEMPOOL_RING 1
#define RTE_DRIVER_MEMPOOL_STACK 1
#undef RTE_LIBRTE_OCTEONTX_MEMPOOL
#undef RTE_LIBRTE_OCTEONTX_MEMPOOL_DEBUG
#define RTE_LIBRTE_MBUF 1
#undef RTE_LIBRTE_MBUF_DEBUG
#define RTE_MBUF_DEFAULT_MEMPOOL_OPS "ring_mp_mc"
#undef RTE_MBUF_SCATTER_GATHER 1
#undef RTE_MBUF_REFCNT_ATOMIC 1
#define RTE_PKTMBUF_HEADROOM 128
#define RTE_LIBRTE_TIMER 1
#undef RTE_LIBRTE_TIMER_DEBUG
#define RTE_LIBRTE_CFGFILE 1
#define RTE_LIBRTE_CMDLINE 1
#undef RTE_LIBRTE_CMDLINE_DEBUG
#define RTE_LIBRTE_HASH 1
#undef RTE_LIBRTE_HASH_DEBUG
#undef RTE_LIBRTE_EFD
#undef RTE_LIBRTE_MEMBER
#define RTE_LIBRTE_JOBSTATS 1
#define RTE_LIBRTE_METRICS 1
#define RTE_LIBRTE_BITRATE 1
#define RTE_LIBRTE_LATENCY_STATS 1
#define RTE_LIBRTE_LPM 1
#undef RTE_LIBRTE_LPM_DEBUG
#define RTE_LIBRTE_ACL 1
#undef RTE_LIBRTE_ACL_DEBUG
#undef RTE_LIBRTE_POWER
#undef RTE_LIBRTE_POWER_DEBUG
#define RTE_MAX_LCORE_FREQS 64
#define RTE_LIBRTE_NET 1
#define RTE_LIBRTE_IP_FRAG 1
#undef CONFIG_RTE_LIBRTE_IP_FRAG_DEBUG
#define RTE_LIBRTE_IP_FRAG_MAX_FRAG 4
#undef RTE_LIBRTE_IP_FRAG_TBL_STAT
#define RTE_LIBRTE_GRO 1 
#define RTE_LIBRTE_GSO 1
#define RTE_LIBRTE_METER 1
#define RTE_LIBRTE_FLOW_CLASSIFY 1
#define RTE_LIBRTE_SCHED 1
#undef CONFIG_RTE_SCHED_DEBUG
#undef CONFIG_RTE_SCHED_RED
#undef RTE_SCHED_COLLECT_STATS
#undef RTE_SCHED_SUBPORT_TC_OV
#define RTE_SCHED_PORT_N_GRINDERS 8
#undef RTE_SCHED_VECTOR
#define RTE_LIBRTE_DISTRIBUTOR 1
#define RTE_LIBRTE_REORDER 1
#define RTE_LIBRTE_PORT 1
#undef RTE_PORT_STATS_COLLECT
#undef RTE_PORT_PCAP
#define RTE_LIBRTE_TABLE 1
#undef RTE_TABLE_STATS_COLLECT
#define RTE_LIBRTE_PIPELINE 1
#undef RTE_PIPELINE_STATS_COLLECT
#undef RTE_LIBRTE_KNI
#undef RTE_LIBRTE_PMD_KNI
#undef RTE_KNI_KMOD
#undef RTE_KNI_KMOD_ETHTOOL
#undef RTE_KNI_PREEMPT_DEFAULT
#undef RTE_LIBRTE_PDUMP
#undef RTE_LIBRTE_VHOST
#undef RTE_LIBRTE_VHOST_NUMA
#undef RTE_LIBRTE_VHOST_DEBUG
#undef RTE_LIBRTE_PMD_VHOST 
#define RTE_APP_TEST 1
#undef RTE_APP_TEST_RESOURCE_TAR
#define RTE_APP_CHKINCS 1
#define RTE_TEST_PMD 1
#undef RTE_TEST_PMD_RECORD_CORE_CYCLES
#undef RTE_TEST_PMD_RECORD_BURST_STATS
#define RTE_APP_CRYPTO_PERF 1
#define RTE_APP_EVENTDEV 1
#define RTE_EAL_PMD_PATH ""
#define RTE_CACHE_LINE_SIZE 64
#define RTE_CACHE_LINE_MIN_SIZE 64
